In [3]:
import numpy as np
import pandas as pd
from sklearn import metrics
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score


In [4]:
df=pd.read_csv('/content/zoo_data (1).csv')

In [5]:
df

1  0  0.1  1.1  0.2  0.3  1.2  1.3  1.4  1.5  0.4  0.5  4  0.6  0.7  1.6  \
0   1  0    0    1    0    0    0    1    1    1    0    0  4    1    0    1   
1   0  0    1    0    0    1    1    1    1    0    0    1  0    1    0    0   
2   1  0    0    1    0    0    1    1    1    1    0    0  4    0    0    1   
3   1  0    0    1    0    0    1    1    1    1    0    0  4    1    0    1   
4   1  0    0    1    0    0    0    1    1    1    0    0  4    1    0    1   
.. .. ..  ...  ...  ...  ...  ...  ...  ...  ...  ...  ... ..  ...  ...  ...   
95  1  0    0    1    0    0    0    1    1    1    0    0  2    1    0    1   
96  1  0    1    0    1    0    0    0    0    1    1    0  6    0    0    0   
97  1  0    0    1    0    0    1    1    1    1    0    0  4    1    0    1   
98  0  0    1    0    0    0    0    0    0    1    0    0  0    0    0    0   
99  0  1    1    0    1    0    0    0    1    1    0    0  2    1    0    0   

    1.7  
0     1  
1     4  
2     1  
3     1  
4     1  
..  ...  
95    1  
96    6  
97    1  
98    7  
99    2  

[100 rows x 17 columns]

In [7]:
x=df.drop('1.7',axis=1).drop('1',axis=1)
y=df['1.7']


In [8]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [10]:
from sklearn.tree import DecisionTreeClassifier
model=DecisionTreeClassifier()
model.fit(x_train,y_train)


DecisionTreeClassifier()

In [11]:
y_pred=model.predict(x_test)

In [12]:
print(confusion_matrix(y_test,y_pred))

[[8 0 0 0 0 0]
 [0 5 0 0 0 0]
 [0 0 0 0 1 0]
 [0 0 0 2 0 0]
 [0 0 0 0 2 0]
 [0 0 0 0 0 2]]


In [13]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           1       1.00      1.00      1.00         8
           2       1.00      1.00      1.00         5
           3       0.00      0.00      0.00         1
           5       1.00      1.00      1.00         2
           6       0.67      1.00      0.80         2
           7       1.00      1.00      1.00         2

    accuracy                           0.95        20
   macro avg       0.78      0.83      0.80        20
weighted avg       0.92      0.95      0.93        20



/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [15]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred))

0.95
