In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as py
from sklearn.metrics import roc_curve



In [ ]:
df=pd.read_csv('/content/data_vowel_bayes.csv',names=['x1','x2','x3','T'])

In [ ]:
df

x1    x2    x3  T
0    700  1500  2600  1
1    550  1550  2400  1
2    700  1500  2600  1
3    700  1600  2700  1
4    550  1600  2600  1
..   ...   ...   ... ..
866  500  1050  2900  6
867  500  1000  3000  6
868  500  1000  2800  6
869  500   900  2800  6
870  500   950  2700  6

[871 rows x 4 columns]

In [ ]:
y=df['T']
x=df.drop('T',axis=1)
x=(x-x.min())/(x.max()-x.min())

In [ ]:
x


x1        x2        x3
0    0.692308  0.432432  0.571429
1    0.461538  0.459459  0.428571
2    0.692308  0.432432  0.571429
3    0.692308  0.486486  0.642857
4    0.461538  0.486486  0.571429
..        ...       ...       ...
866  0.384615  0.189189  0.785714
867  0.384615  0.162162  0.857143
868  0.384615  0.162162  0.714286
869  0.384615  0.108108  0.714286
870  0.384615  0.135135  0.642857

[871 rows x 3 columns]

In [ ]:
y


0      1
1      1
2      1
3      1
4      1
      ..
866    6
867    6
868    6
869    6
870    6
Name: T, Length: 871, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=0)
# With random_state=0 , we get the same train and test sets across different executions.

In [ ]:
from sklearn.naive_bayes import GaussianNB
model=GaussianNB()
model.fit(x_train,y_train)

GaussianNB()

In [ ]:
y_preds=model.predict(x_test)

In [ ]:
from sklearn import metrics
print("NB model accuracy(in %):",metrics.accuracy_score(y_test,y_preds))

NB model accuracy(in %): 0.7706422018348624


In [ ]:
matrix=metrics.confusion_matrix(y_test,y_preds)
print(matrix)

[[10  7  0  0  1  2]
 [ 1 17  0  0  0  0]
 [ 0  0 40  0  4  0]
 [ 1  0  0 31  0  5]
 [ 7  0  7  0 40  6]
 [ 0  1  0  7  1 30]]


In [ ]:
cr=metrics.classification_report(y_test,y_preds)
cr

'              precision    recall  f1-score   support\n\n           1       0.53      0.50      0.51        20\n           2       0.68      0.94      0.79        18\n           3       0.85      0.91      0.88        44\n           4       0.82      0.84      0.83        37\n           5       0.87      0.67      0.75        60\n           6       0.70      0.77      0.73        39\n\n    accuracy                           0.77       218\n   macro avg       0.74      0.77      0.75       218\nweighted avg       0.78      0.77      0.77       218\n'